from typing import Optional

from pydantic import BaseModel, Field


class CreateTokenPayload(BaseModel):
    customer_id: str = Field(..., min_length=1)
    customer_name: Optional[str] = None
    branch_id: str
    service_id: str
    lang: str = "en"


class TokenRecord(BaseModel):
    token_id: str
    token_number: str
    customer_id: str
    customer_name: Optional[str] = None
    branch_id: str
    branch_name: str
    service_id: str
    service_name: str
    status: str  # "waiting" | "called" | "served" | "cancelled"
    position_in_queue: int
    created_at: str
    is_prototype: bool = True
    disclaimer: str = (
        "This is a prototype digital queue token generated by Bank Saathi. "
        "It is NOT an official bank-issued token and is not connected to any "
        "real bank branch system."
    )
